"""
Django settings for innovyx_hrms project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
DEBUG=True
load_dotenv(BASE_DIR / '.env', override=True)
GOOGLE_CLIENT_ID_RAW = os.getenv("GOOGLE_CLIENT_ID") or os.getenv("GMAIL_CLIENT_ID")
if GOOGLE_CLIENT_ID_RAW and "," in GOOGLE_CLIENT_ID_RAW:
    GOOGLE_CLIENT_ID = [cid.strip() for cid in GOOGLE_CLIENT_ID_RAW.split(",") if cid.strip()]
else:
    GOOGLE_CLIENT_ID = GOOGLE_CLIENT_ID_RAW
if not GOOGLE_CLIENT_ID and DEBUG:
    import warnings
    warnings.warn(
        "GOOGLE_CLIENT_ID is not set in .env — POST /app/google-login/ will fail token verification.",
        stacklevel=1,
    )


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-v++-2-a@y^9k1+kky5l^fg6#r1hc)hd(fwjox62c7@=ccvdkff'

# SECURITY WARNING: don't run with debug turned on in production!


# ALLOWED_HOSTS = ['apihrms.innovyxtechlabs.com']
ALLOWED_HOSTS = ['apihrms.innovyxtechlabs.com', 'localhost', '127.0.0.1', '10.209.43.199', '192.168.0.3', '192.168.1.10', '192.168.1.3', '10.20.72.169']
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'drf_yasg',
    'corsheaders',
    'channels',
    'app',
    'employee',
    'notifications',
    'website'
]

# Celery / periodic tasks
INSTALLED_APPS += [
    'django_celery_beat',
    'django_apscheduler',
    'django_celery_results',
]



AUTH_USER_MODEL = 'app.UserRegister'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
}

SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header',
            'description': "JWT Authorization header using the Bearer scheme. Example: **'Bearer your_token_here'**",
        }
    },
}


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
]

ROOT_URLCONF = 'innovyx_hrms.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

ASGI_APPLICATION = 'innovyx_hrms.asgi.application'

WSGI_APPLICATION = 'innovyx_hrms.wsgi.application'

# Channels / WebSocket (Redis)
# REDIS_URL may include a DB suffix; keep for Channels default (usually DB 0)
REDIS_URL = os.getenv("REDIS_URL", "redis://127.0.0.1:6379/0")
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {"hosts": [REDIS_URL]},
    }
}


FCM_CREDENTIALS_FILE = BASE_DIR / "firebase-service-account.json"

FCM_PROJECT_ID = "peoplesuite-ca155"


# SITE_URL = "https://apihrms.innovyxtechlabs.com/"
SITE_URL = "http://localhost:8000/"


# CORS_ALLOW_ALL_ORIGINS = True
# CORS_ALLOW_ALL_HEADERS = True
# CORS_ALLOW_CREDENTIALS = True

SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin-allow-popups'

CORS_ALLOWED_ORIGINS = [
    "https://hrms.innovyxtechlabs.com",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:3009",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]


CSRF_TRUSTED_ORIGINS = [
    "https://hrms.innovyxtechlabs.com",
    "http://localhost:3000",
    "http://localhost:3009",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]

# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:3000",
# ]


CORS_ALLOW_HEADERS = [
    'content-type',
    'authorization',
    'cache-control',
    'x-requested-with',
    'accept',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-forwarded-for',
]

CORS_ALLOW_METHODS = ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        # 'NAME': 'innovyx_hrms_pr',
        'NAME': 'hrms_db',
        'USER': 'postgres',
        'PASSWORD': '1234',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'alerts@innovyxtechlabs.com'
EMAIL_HOST_PASSWORD = 'ebrhnknvfngrloum'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True
TIME_ZONE = 'Asia/Kolkata'



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Celery configuration — use separate Redis DB numbers for isolation
# Provide a base Redis URL without DB (e.g. REDIS_URL_BASE=redis://127.0.0.1:6379)
REDIS_URL_BASE = os.getenv('REDIS_URL_BASE')
if not REDIS_URL_BASE:
    # fall back to REDIS_URL without DB suffix if provided, else default
    r = os.getenv('REDIS_URL', 'redis://127.0.0.1:6379/0')
    # strip any trailing /<db>
    if '/' in r.rsplit('/', 1)[-1]:
        REDIS_URL_BASE = r
    else:
        # remove DB suffix if present
        REDIS_URL_BASE = r.rsplit('/', 1)[0]

# DB indexes for isolation (defaults: channels DB 0, broker DB 1, results DB 2)
CELERY_REDIS_DB_BROKER = os.getenv('CELERY_REDIS_DB_BROKER', '1')
CELERY_REDIS_DB_RESULTS = os.getenv('CELERY_REDIS_DB_RESULTS', '2')

# redis:// URLs — append ?protocol=2 so redis-py 6+ doesn't send HELLO (requires Redis 6+)
CELERY_BROKER_URL = f"{REDIS_URL_BASE}/{CELERY_REDIS_DB_BROKER}?protocol=2"
CELERY_RESULT_BACKEND = f"{REDIS_URL_BASE}/{CELERY_REDIS_DB_RESULTS}?protocol=2"

# Use Redis scheduler via django-celery-beat's database scheduler (keeps schedule in Django DB)
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

from celery.schedules import crontab
CELERY_BEAT_SCHEDULE = {
    # Activate cycles whose start_date has arrived; complete when deadline passed
    'sync-appraisal-cycle-statuses': {
        'task': 'employee.tasks.sync_appraisal_cycle_statuses',
        'schedule': crontab(minute=0),  # every hour on the hour
    },
}

# Celery serialization settings
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

# Logging — makes scheduler and task output visible in the Django console
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {
            'format': '[%(asctime)s] %(levelname)s %(name)s: %(message)s',
            'datefmt': '%H:%M:%S',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'employee': {          # covers employee.apps, employee.tasks
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'notifications': {     # covers notifications.service, etc.
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'apscheduler': {       # APScheduler internal logs
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}
