# Generated by Django 5.2.4 on 2026-04-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_userregister_email'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='employee',
                    name='gmail_connected',
                    field=models.BooleanField(default=False),
                ),
            ],
        ),
    ]
