# Generated by Django 5.0.1 on 2026-04-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_employee_gmail_connected'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='company',
                    name='gmail_domains',
                    field=models.TextField(blank=True, null=True),
                ),
            ],
        )
    ]
