# Generated by Django 5.2.4 on 2025-07-21 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_department_level_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to='company/assets/')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='app.company')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=10, null=True, unique=True)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=50, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('mobile', models.CharField(max_length=11, null=True)),
                ('temporary_address', models.CharField(blank=True, max_length=255, null=True)),
                ('permanent_address', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('aadhar_no', models.CharField(blank=True, max_length=100, null=True)),
                ('aadhar_card', models.ImageField(blank=True, null=True, upload_to='documents')),
                ('pan_no', models.CharField(blank=True, max_length=100, null=True)),
                ('pan_card', models.ImageField(blank=True, null=True, upload_to='documents')),
                ('guardian_name', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_mobile', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('previous_employer', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_releaving', models.DateField(blank=True, null=True)),
                ('previous_designation_name', models.CharField(blank=True, max_length=100, null=True)),
                ('previous_salary', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('ctc', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('gross_salary', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('epf_status', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=50, null=True)),
                ('uan', models.CharField(blank=True, max_length=50, null=True)),
                ('source_of_employment', models.CharField(blank=True, choices=[('internalreference', 'Internal Reference'), ('linkedin', 'LinkedIn'), ('walkin', 'Walk In'), ('socialmedia', 'Social Media')], max_length=50, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank', 'Bank')], max_length=50, null=True)),
                ('account_no', models.CharField(blank=True, max_length=20, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=50, null=True)),
                ('esic_status', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=50, null=True)),
                ('esic_no', models.CharField(blank=True, max_length=50, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='app.company')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='app.department')),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='app.designation')),
                ('reporting_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportees', to='app.employee')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('who_referred', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_referred_by_me', to='app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeAssetDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assetinventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_employees', to='app.assetinventory')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_assignments', to='app.employee')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='asset_details',
            field=models.ManyToManyField(blank=True, through='app.EmployeeAssetDetails', to='app.assetinventory'),
        ),
    ]
