# Generated by Django 5.2.4 on 2025-07-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_salarystructure_conveyance_percent_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='departmentwiseworkingdays',
            unique_together={('department',)},
        ),
        migrations.AddField(
            model_name='departmentwiseworkingdays',
            name='shifts',
            field=models.ManyToManyField(blank=True, to='app.shiftpolicy'),
        ),
        migrations.RemoveField(
            model_name='departmentwiseworkingdays',
            name='shift',
        ),
    ]
