# Generated by Django 5.2.4 on 2025-07-21 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_assetinventory_employee_employeeassetdetails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='app.level'),
        ),
    ]
