# Generated by Django 5.2.4 on 2025-07-28 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_departmentwiseworkingdays_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='departmentwiseworkingdays',
            unique_together=set(),
        ),
    ]
