# Generated by Django 5.2.4 on 2025-07-28 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_departmentwiseworkingdays_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departmentwiseworkingdays',
            options={'verbose_name_plural': 'Department Wise Working Days'},
        ),
    ]
