# Generated by Cursor on 2026-04-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_chatconversation_chatconversationmember_chatmessage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatconversationmember",
            name="last_seen_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]

