# Generated by Django 5.2.4 on 2025-07-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_departmentwiseworkingdays_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departmentwiseworkingdays',
            options={},
        ),
        migrations.AlterField(
            model_name='departmentwiseworkingdays',
            name='week_end_day',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='departmentwiseworkingdays',
            name='week_start_day',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='departmentwiseworkingdays',
            name='working_days_count',
            field=models.IntegerField(),
        ),
    ]
