# Generated by Django 5.2.4 on 2025-07-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_departmentwiseworkingdays_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departmentwiseworkingdays',
            options={'verbose_name_plural': 'Department Wise Working Days'},
        ),
        migrations.AlterField(
            model_name='departmentwiseworkingdays',
            name='working_days_count',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
