# Generated by Cursor on 2026-04-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_chatconversationmember_last_seen_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to="chat_attachments/"),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="attachment_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="attachment_mime",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]

