# Generated by Django 5.2.4 on 2026-04-17 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_chatmessage_attachments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoogleOAuthToken',
        ),
    ]
