# Generated by Django 5.2.4 on 2025-07-30 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_departmentwiseworkingdays_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='app.department'),
        ),
    ]
