# Generated by Django 5.2.4 on 2025-07-30 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_level_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='department',
        ),
    ]
