# Generated by Cursor on 2026-04-17
#
# NOTE: This is a state-only change (choices) so no DB operation is required.

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0009_delete_googleoauthtoken"),
    ]

    operations = []

