# Generated by Django 5.2.4 on 2025-08-01 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_level_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companypolicies',
            name='description',
        ),
    ]
