# Generated by Django 5.2.4 on 2026-04-18 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_chatconversationmember_add_viewer_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatconversationmember',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member'), ('viewer', 'Viewer')], default='member', max_length=10),
        ),
    ]
