# Generated by Django 5.2.4 on 2025-08-02 04:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_companypolicies_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='payroll_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
