# Generated by Django 5.0.1 on 2026-04-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_chatconversationmember_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentwiseworkingdays',
            name='weekend_days',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='departmentwiseworkingdays',
            name='working_days',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='departmentwiseworkingdays',
            name='week_end_day',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='departmentwiseworkingdays',
            name='week_start_day',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
