# Generated by Django 5.0.1 on 2026-04-20 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import Q


def forwards_migrate_legacy_inventory(apps, schema_editor):
    AssetInventory = apps.get_model('app', 'AssetInventory')
    EmployeeAssetDetails = apps.get_model('app', 'EmployeeAssetDetails')
    SupplyItem = apps.get_model('app', 'SupplyItem')
    EmployeeSupplyAssignment = apps.get_model('app', 'EmployeeSupplyAssignment')

    id_map = {}
    for ai in AssetInventory.objects.all():
        assigned = EmployeeAssetDetails.objects.filter(assetinventory_id=ai.id).count()
        total = max(int(ai.quantity or 0) + assigned, 0)
        avail = max(int(ai.quantity or 0), 0)
        si = SupplyItem.objects.create(
            company_id=ai.company_id,
            item_code=f'LEGACY-{ai.id}',
            item_name=(ai.name or 'Migrated item')[:255],
            sub_category='other',
            total_stock=total,
            available_quantity=avail,
            reorder_level=0,
            unit_price=None,
            last_restocked=None,
            vendor_details=None,
            unit_of_measure='pcs',
            notes=(ai.description or '')[:2000] if ai.description else None,
        )
        id_map[ai.id] = si.id

    for ead in EmployeeAssetDetails.objects.all():
        new_sid = id_map.get(ead.assetinventory_id)
        if not new_sid:
            continue
        EmployeeSupplyAssignment.objects.create(
            employee_id=ead.employee_id,
            supply_item_id=new_sid,
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_departmentwiseworkingdays_weekend_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=64)),
                ('item_name', models.CharField(max_length=255)),
                ('sub_category', models.CharField(choices=[('peripherals', 'Peripherals'), ('stationery', 'Stationery'), ('swag', 'Swag'), ('cables', 'Cables'), ('other', 'Other')], default='other', max_length=32)),
                ('total_stock', models.PositiveIntegerField(default=0)),
                ('available_quantity', models.PositiveIntegerField(default=0)),
                ('reorder_level', models.PositiveIntegerField(default=0)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('last_restocked', models.DateField(blank=True, null=True)),
                ('vendor_details', models.TextField(blank=True, null=True)),
                ('unit_of_measure', models.CharField(choices=[('pcs', 'Pcs'), ('box', 'Box'), ('pack', 'Pack'), ('meters', 'Meters')], default='pcs', max_length=16)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_items', to='app.company')),
            ],
            options={
                'ordering': ['item_code'],
            },
        ),
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_tag', models.CharField(max_length=64)),
                ('serial_number', models.CharField(blank=True, max_length=128, null=True)),
                ('category', models.CharField(choices=[('laptop', 'Laptop'), ('monitor', 'Monitor'), ('server', 'Server'), ('furniture', 'Furniture'), ('other', 'Other')], default='other', max_length=32)),
                ('model_brand', models.CharField(blank=True, max_length=255, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('assignment_date', models.DateField(blank=True, null=True)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_use', 'In-Use'), ('repair', 'Repair'), ('available', 'Available'), ('scrapped', 'Scrapped')], default='available', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_assets_assigned', to='app.employee')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_assets', to='app.company')),
            ],
            options={
                'ordering': ['asset_tag'],
            },
        ),
        migrations.CreateModel(
            name='AssetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='asset_requests/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_requests', to='app.company')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_requests_submitted', to='app.employee')),
                ('related_fixed_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='app.fixedasset')),
                ('related_supply_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='app.supplyitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeSupplyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_assignments', to='app.employee')),
                ('supply_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_assignments', to='app.supplyitem')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AssetSupportingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(upload_to='asset_documents/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('asset_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='app.assetrequest')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_documents', to='app.company')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_asset_documents', to=settings.AUTH_USER_MODEL)),
                ('fixed_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='app.fixedasset')),
                ('supply_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='app.supplyitem')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.RunPython(forwards_migrate_legacy_inventory, noop_reverse),
        migrations.RemoveField(
            model_name='employee',
            name='asset_details',
        ),
        migrations.AddField(
            model_name='employee',
            name='supply_items',
            field=models.ManyToManyField(blank=True, related_name='employees_assigned', through='app.EmployeeSupplyAssignment', to='app.supplyitem'),
        ),
        migrations.DeleteModel(
            name='EmployeeAssetDetails',
        ),
        migrations.DeleteModel(
            name='AssetInventory',
        ),
        migrations.AddConstraint(
            model_name='fixedasset',
            constraint=models.UniqueConstraint(fields=('company', 'asset_tag'), name='uniq_fixed_asset_tag_per_company'),
        ),
        migrations.AddConstraint(
            model_name='supplyitem',
            constraint=models.UniqueConstraint(fields=('company', 'item_code'), name='uniq_supply_item_code_per_company'),
        ),
        migrations.AddConstraint(
            model_name='assetsupportingdocument',
            constraint=models.CheckConstraint(
                check=(
                    Q(fixed_asset__isnull=False, supply_item__isnull=True, asset_request__isnull=True)
                    | Q(fixed_asset__isnull=True, supply_item__isnull=False, asset_request__isnull=True)
                    | Q(fixed_asset__isnull=True, supply_item__isnull=True, asset_request__isnull=False)
                ),
                name='asset_doc_exactly_one_parent',
            ),
        ),
    ]
