# Generated by Django 5.2.4 on 2025-08-09 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_payroll_payroll_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='reporting_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reporting_level', to='app.level'),
        ),
    ]
