# Generated by Django 5.2.4 on 2025-08-11 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_employee_reporting_level'),
        ('app', '0013_userregister_created_by'),
    ]

    operations = [
    ]
