# Generated by Django 5.0.1 on 2026-04-20 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_inventory_and_supply'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedasset',
            name='variable_supply_item',
            field=models.ForeignKey(blank=True, help_text='Variable (SKU) catalog row this core unit is tied to, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_asset_instances', to='app.supplyitem'),
        ),
    ]
