# Generated by Django 5.2.4 on 2025-08-13 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_merge_20250811_0949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breaklog',
            old_name='break_policy',
            new_name='break_config',
        ),
        migrations.RemoveField(
            model_name='breakconfig',
            name='break_type',
        ),
        migrations.AddField(
            model_name='breakconfig',
            name='break_choice',
            field=models.CharField(blank=True, choices=[('dont_disturb', "Don't Disturb"), ('short_break', 'Short Break'), ('meal_break', 'Meal Break')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='breakconfig',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='breakconfig',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='break_configs', to='app.company'),
        ),
        migrations.AlterField(
            model_name='breakconfig',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='breaklog',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='break_logs', to='app.employee'),
        ),
    ]
