# Generated by Django 5.2.4 on 2025-08-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_lettertemplate_generatedletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedletter',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
