# Generated by Django 5.2.4 on 2025-08-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_generatedletter_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedletter',
            name='file_path',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
