# Generated by Django 5.2.4 on 2025-08-28 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_generatedletter_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedletter',
            name='relieved_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.relievedemployee'),
        ),
    ]
