# Generated by Django 5.2.4 on 2025-08-28 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_generatedletter_relieved_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedletter',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
