# Generated by Django 5.2.4 on 2025-08-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_generatedletter_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedletter',
            name='type',
            field=models.CharField(blank=True, choices=[('offer', 'Offer'), ('appointment', 'Appointment'), ('relieve', 'Relieve')], max_length=20, null=True),
        ),
    ]
