# Generated by Django 5.2.4 on 2025-08-29 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_generatedletter_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relievedemployee',
            name='employee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relieved_info', to='app.employee'),
        ),
    ]
