# Generated by Django 5.2.4 on 2025-08-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_relievedemployee_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='aadhar_card',
            field=models.FileField(blank=True, null=True, upload_to='documents'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pan_card',
            field=models.FileField(blank=True, null=True, upload_to='documents'),
        ),
    ]
