# Generated by Django 5.2.4 on 2025-09-01 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_employee_aadhar_card_alter_employee_pan_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='lettertemplate',
            name='email_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
