# Generated by Django 5.2.4 on 2025-09-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_lettertemplate_email_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedletter',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generatedletter',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
