# Generated by Django 5.2.4 on 2025-10-08 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_generatedletter_email_sent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='who_referred',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
