# Generated by Django 5.2.4 on 2025-10-08 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_employee_who_referred'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='aadhar_card',
            field=models.FileField(blank=True, null=True, upload_to='employee/aadhar'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pan_card',
            field=models.FileField(blank=True, null=True, upload_to='employee/pancard'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='employee/photos'),
        ),
    ]
