# Generated by Django 5.2.4 on 2025-10-10 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_employee_aadhar_card_alter_employee_pan_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='shift_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_employee', to='app.shiftpolicy'),
        ),
    ]
