# Generated by Django 5.2.4 on 2025-10-10 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_employee_shift_assigned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='shift',
        ),
    ]
