# Generated by Django 5.2.4 on 2025-10-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='last_active',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('away', 'Away'), ('dnd', 'Do Not Disturb'), ('offline', 'Offline')], default='offline', max_length=20),
        ),
    ]
