# Generated by Django 5.0.1 on 2025-12-06 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_employee_last_active_employee_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleave',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
