# Generated by Django 5.0.1 on 2025-12-09 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_officefloor_officesection_officeseat'),
    ]

    operations = [
        migrations.AddField(
            model_name='officeseat',
            name='rotation',
            field=models.FloatField(default=0),
        ),
    ]
