# Generated by Django 5.0.1 on 2025-12-09 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_officeseat_rotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='officesection',
            name='rotation',
            field=models.FloatField(default=0),
        ),
    ]
